### ISSUE TITLE
Alternative URLs for Regions

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#565]
When entering `/cologne` it should redirect to `/koeln`

**Comment by gill0r** [comment]
Sounds like a good idea to me!

I'd like to implement this. Since I haven't had much contact with Ruby and Rails by now I think this is a nice starter to learn.

I was wondering how to handle multiple slugs and came up with these options:
1. Should we just add an (one) alternative slug to `Region`, or
2. add alternative slugs with a 1:n/`has_many` to `RegionSlugs`? 

I'd prefer option 2, since we probably want to keep and redirect to a *main slug* (`Region.slug`, e.g. `/koeln`) and maybe also want to use `/colonia` (Spanish) for it in the future. Which leads me to the question: is there a *nicer* way in Rails instead of creating a `RegionSlugs` model just for containing a string (the slug)?

So, what would I do?
1. make sure alternative slug/`RegionSlug.slug` is unique
2. overwrite/create `Region.find_by_slug` to take all slugs into account. Maybe rename `Region.slug` to `Region.main_slug`?
3. update EventController to check if given region-slug is the main slug. If not redirect (HTTP 302) to it.
4. make sure slugs are available in administration for CRUD operations (how to write a test for that?)

Did I miss something? Is this the way one would implement this in Rails?

I'm happy to read your comments on this.

**Comment by moonglum** [comment]
I think I would do it slightly different:

* Remove the slug attribute from the RegionSlug class/table.
* Implement a `RegionSlug` class. Every `RegionSlug` has a `slug` attribute.
* A `Region` `has_many` `RegionSlugs`, but one of them is the main slug (I would say by having a `has_one as:`). The main slug will be returned when `Region.slug` is called.
* The RegionSlug will get the `find_by_slug` method.

What do you think? In my opinion this is a little bit more straightforward as there's only one place to look up slugs – and not two (one for alternative slugs (the `RegionSlug`) and one for main slugs (the `Region`))

**Comment by gill0r** [comment]
That sounds great and is cleaner (only one class for representing a slug, not a string and a class) than my first approach. I think I will do it this way. :)

**Comment by moonglum** [comment]
Great :smile:

**Comment by bascht** [comment]
@gill0r Is this still *in progress* – can we review / help out with something? Just checking so this ticket doesn't grow hoary. :)

**Comment by gill0r** [comment]
Hey,
thanks for checking! :) Yes, this is still *in progress* but I need some help. I commented on this commit in the [branch](https://github.com/hacken-in/website/compare/565-alternative-urls-for-region) where I got stuck: https://github.com/hacken-in/website/commit/4b625472c614f327ab78092fdfd49b18cb53c101

Since I'm moving to Berlin next week, I can't promise I will be able to implement the feature during the next 2 weeks. But I'm still willing to learn & implement! :)

**Comment by gill0r** [comment]
FYI: I started implementing the feature yesterday, but did not complete it yet. You can see the progress in the branch [`565-alternative-urls-for-region-3`](https://github.com/hacken-in/website/tree/565-alternative-urls-for-region-3). I hope to make some progress during this week.

**Comment by moonglum** [comment]
Awesome!

**Comment by moonglum** [comment]
@gill0r Hello :heart: Are you still interested in working on this? :smile:

**Comment by gill0r** [comment]
@moonglum Oh yes, I'd love to. Unfortunately my weeks and weekends are really busy. If someone else wants to implement this, feel free to do it. Otherwise I'd do it, but can't state an ETA, sorry :(

**Comment by moonglum** [comment]
No worries, @gill0r :heart: Current focus is the migration to Uberspace. After that, I'll look into open PRs / issues again :smile:
