### ISSUE TITLE
NoMethodError in single_events#show

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#595]
## Exception in Hacken.in

**NoMethodError** in **single_events#show**
undefined method &#x60;strftime&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5546b2f4d4b5f4b0e49f27f3?event_id=5546b86c4198660023bb550a)
## Stacktrace

```
app/models/single_event.rb:116 - name_with_date
app/models/single_event.rb:155 - to_opengraph
app/controllers/single_events_controller.rb:8 - show
```

[View full stacktrace](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5546b2f4d4b5f4b0e49f27f3?event_id=5546b86c4198660023bb550a)

**Comment by bascht** [comment]
Change bde1260d already had a `TODO: Fix resulting bugs in views` but this looks more like someone forgot to do their nil-checks:

```ruby
"#{self.full_name} am #{self.occurrence.strftime("%d.%m.%Y um %H:%M")}"
```

**Comment by moonglum** [comment]
Nil *shakes fist*

**Comment by bascht** [comment]
The issue is still [reproducible](https://hacken.in/events/240-webworker-nrw/dates/2516), so I dug a bit into the production database and it looks like there are two faulty `SingleEvents` with no `occurrence` and there is not much we do here, as this constraint isn't validated anywhere (probably a relict from our MySQL switch #364):

```sql
SELECT id, name, created_at, occurrence FROM single_events WHERE occurrence is NULL;
  id  | name |     created_at      | occurrence 
------+------+---------------------+------------
 3290 |      | 2014-01-27 20:33:33 | 
 2516 |      | 2013-09-06 08:57:56 | 
(2 rows)
```

My proposed fix: Set an arbitrary date from the past and let's never talk about them again. E.g.

```sql
UPDATE single_events SET occurrence='2013-06-22 22:00:00' WHERE id IN (2516,3290);
```

Yay, nay? :)

**Comment by moonglum** [comment]
Yay!

**Comment by moonglum** [comment]
Do it, @bascht

**Comment by moonglum** [comment]
Never occurred again.
